global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pushgateway
  - job_name: 'pushgateway'
    honor_labels: true  # Critical: preserve labels from pushgateway
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Grafana (optional - for monitoring Grafana itself)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

